<a href="https://colab.research.google.com/github/jadhav-rakesh/ML/blob/main/ds1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#You need to create a vector.

vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [4]:
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

In [5]:
#You need to create a matrix.

matrix = np.array([[1,2],
                   [3,4],
                   [5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
matrix_object = np.mat([[1,2],
                        [3,4],
                        [5,6]])
matrix_object

matrix([[1, 2],
        [3, 4],
        [5, 6]])

- A sparse matrix is a matrix in which most elements are 0

In [7]:
#Given data with very few nonzero values, you want to efficiently represent it.

from scipy import sparse

matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])

print(matrix)

matrix_sparse = sparse.csr_matrix(matrix)  # compressed sparse row (CSR) matrices
print("\n",matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]

   (1, 1)	1
  (2, 0)	3


In [8]:
#You need to preallocate arrays of a given size with some value.

vector = np.zeros(shape = 5)
vector

array([0., 0., 0., 0., 0.])

In [9]:
matrix = np.full(shape=(3,3), fill_value=1)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
#You need to select one or more elements in a vector or matrix.

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(vector[2])
print(matrix[1, 1])

3
5


In [11]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [12]:
vector[:3]

array([1, 2, 3])

In [13]:
vector[3:]

array([4, 5, 6])

In [14]:
vector[-1]

6

In [15]:
#Reverse the vector
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [16]:
#first 2 rows, all columns

matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#all rows, 2nd column

matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [19]:
#You want to describe the shape, size, and dimensions of a matrix.

matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])


print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2


In [20]:
#You want to apply some function to all elements in an array.

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

add_100 = lambda i: i + 100

vectorized_add_100 = np.vectorize(add_100)

vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [23]:
#find the maximum or minimum value in an array.

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(np.max(matrix))
print(np.min(matrix))

9
1


In [24]:
#maximum along each column

np.max(matrix, axis=0)

array([7, 8, 9])

In [25]:
#maximum along each row

np.max(matrix, axis=1)

array([3, 6, 9])

In [26]:
#calculate some descriptive statistics about an array.

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

np.mean(matrix)

5.0

In [27]:
np.var(matrix)

6.666666666666667

In [28]:
np.std(matrix)

2.581988897471611

In [29]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [30]:
#change the shape (number of rows and columns) of an array without changing the element values.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [34]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
#transpose a vector or matrix.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
#a vector can’t be transposed because it’s just a collection of values
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [38]:
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
# transform a matrix into a one-dimensional array

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

-  Unlike flatten, which returns a copy of the original array, ravel operates on the original object itself and is therefore slightly faster. It also lets us flatten lists of arrays, which we can’t do with the flatten method.

In [41]:
matrix_A = np.array([[1, 2],
                     [3, 4]])
matrix_B = np.array([[5, 6],
                     [7, 8]])
matrix_C = [matrix_A, matrix_B]

np.ravel(matrix_C)

array([1, 2, 3, 4, 5, 6, 7, 8])

- The maximum number of linearly independent rows in a matrix A is called the row rank of A, and the maximum number of linarly independent columns in A is called the column rank of A

In [42]:
#know the rank(The rank of a matrix is the dimensions of the vector
#               space spanned by its columns or rows.) of a matrix

matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

np.linalg.matrix_rank(matrix)

2

In [43]:
#get the diagonal elements of a matrix.

matrix.diagonal()

array([ 1,  1, 15])

In [44]:
#diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([ 1, 10])

In [45]:
# diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([1, 1])

In [47]:
#calculate the trace of a matrix.(The trace of a matrix is the sum of the diagonal elements )

matrix.trace()

17

In [48]:
#calculate the dot product of two vectors.

vector_A = np.array([1, 2, 3])
vector_B = np.array([4, 5, 6])

np.dot(vector_A, vector_B)

32

In [49]:
vector_A @ vector_B

32

In [50]:
#add or subtract two matrices

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [53]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [54]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [55]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [56]:
#multiply two matrices.

np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [57]:
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [58]:
#element wise multiplication

matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [61]:
# calculate the inverse of a square matrix.

matrix = np.array([[1, 4],
                   [2, 5]])

np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [62]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [63]:
#generate pseudorandom values.

np.random.seed(42)

## Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.37454012, 0.95071431, 0.73199394])

In [64]:
np.random.randint(0, 11, 3)

array([4, 6, 9])

In [65]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0

np.random.normal(0.0, 1.0, 3)

array([ 0.27904129,  1.01051528, -0.58087813])

In [66]:
np.random.uniform(1.0, 2.0, 3)

array([1.18340451, 1.30424224, 1.52475643])