<a href="https://colab.research.google.com/github/jadhav-rakesh/ML/blob/main/ds13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Regression

In [1]:
import numpy as np
import pandas as pd

#Fitting a Line

In [2]:
#train a model that represents a linear relationship between the feature and target vector.

from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

regression = LinearRegression()

model = regression.fit(features, target)

In [3]:
model.intercept_

-0.009650118178816669

In [4]:
model.coef_

array([1.95531234e-02, 4.42087450e+01, 5.81494563e+01])

In [5]:
target[0]

-20.870747595269407

In [6]:
model.predict(features)[0]

-20.861927709296808

In [7]:
print(model.score(features, target))

0.9999901732607787


#Handling Interactive Effects

In [8]:
#You have a feature whose effect on the target variable depends on another feature.

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

features ,target = make_regression(n_samples=100,
                                   n_features=2,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

interaction = PolynomialFeatures(degree=3, include_bias=False, interaction_only=True)

features_interaction = interaction.fit_transform(features)

regression = LinearRegression()

model = regression.fit(features_interaction, target)

In [9]:
features[0]

array([0.0465673 , 0.80186103])

In [10]:
interaction_term = np.multiply(features[:, 0], features[:, 1])
interaction_term[0]

0.037340501965846186

In [11]:
features_interaction[0]

array([0.0465673 , 0.80186103, 0.0373405 ])

#Fitting a Nonlinear Relationship

In [12]:
#model a nonlinear relationship.

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=42)

polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

regression = LinearRegression()

model = regression.fit(features_polynomial, target)

In [13]:
features[0]

array([-0.51827022,  1.47789404,  0.35711257])

In [14]:
features[0]**2

array([0.26860402, 2.18417081, 0.12752939])

In [15]:
features[0]**3

array([-0.13920946,  3.22797303,  0.04554235])

In [16]:
features_polynomial[0]

array([-0.51827022,  1.47789404,  0.35711257,  0.26860402, -0.76594847,
       -0.18508081,  2.18417081,  0.52777454,  0.12752939, -0.13920946,
        0.39696828,  0.09592187, -1.13199068, -0.27352983, -0.06609468,
        3.22797303,  0.77999485,  0.18847492,  0.04554235])

# Reducing Variance with Regularization

In [17]:
#shrinkage penalty (also called regularization) like ridge regression and lasso regression

from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=1)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

regression = Ridge(alpha=0.5)

model = regression.fit(features_standardized, target)

* In ridge regression, the shrinkage penalty is a tuning hyperparameter multiplied by the squared sum of all coefficients:

* he lasso is similar, except the shrinkage penalty is a tuning hyperparameter multiplied by the sum of the absolute value of all coefficients:

* ridge regression often produces slightly better predictions than lasso
*  If we want a balance between ridge and lasso’s penalty functions we can use elastic net, which is simply a regression model with both penalties included.

In [18]:
from sklearn.linear_model import RidgeCV

regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

model_cv = regr_cv.fit(features_standardized, target)

model_cv.coef_

array([1.29223201e-02, 4.40972291e+01, 5.38979372e+01])

In [19]:
model_cv.alpha_

0.1

#Reducing Features with Lasso Regression

In [20]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

features, target = make_regression(n_samples=100,
                                   n_features=3,
                                   n_informative=2,
                                   n_targets=1,
                                   noise=0.2,
                                   coef=False,
                                   random_state=42)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

regerssion = Lasso(alpha=0.5)

model = regression.fit(features_standardized, target)

In [21]:
model.coef_


array([-0.05185633, 17.20798734, 22.99988714])

In [22]:
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.       ,  6.7953537, 12.6147187])