<a href="https://colab.research.google.com/github/jadhav-rakesh/ML/blob/main/ds18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Bayes

In [1]:
import numpy as np
import pandas as pd

#Training a Classifier for Continuous Features

In [2]:
#normal distributed data

from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

features, target = iris.data, iris.target

classifier = GaussianNB()

model = classifier.fit(features, target)

In [3]:
new_observation = [[4, 4, 4, 0.4]]

model.predict(new_observation)

array([1])

In [4]:
#prior probablities
clf = GaussianNB(priors=[0.25, 0.25, 0.5])

model = classifier.fit(features, target)

In [5]:
model.predict(new_observation)

array([1])

#Training a Classifier for Discrete and Count Features

In [7]:
#multinomially distributed
#discrete data (e.g., movie ratings ranging from 1 to 5)

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

text_data = np.array(['I love Brazil. Brazil!',
                      'Brazil is best',
                      'Germany beats both'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

features = bag_of_words.toarray()

target = np.array([0, 0, 1])


classifier = MultinomialNB(class_prior=[0.25, 0.5])

model = classifier.fit(features, target)

In [8]:
new_observation = [[0, 0, 0, 1, 0, 1, 0]]

model.predict(new_observation)

array([0])

#Training a Naive Bayes Classifier for Binary Features

In [9]:
from sklearn.naive_bayes import BernoulliNB

features = np.random.randint(2, size=(100, 3))

target = np.random.randint(2, size=(100, 1)).ravel()

classifier = BernoulliNB(class_prior=[0.25, 0.5])

model.fit(features, target)

MultinomialNB(class_prior=[0.25, 0.5])

In [10]:
model_uniform_prior = BernoulliNB(class_prior=None, fit_prior=False)

#Calibrating Predicted Probabilities

In [11]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV

iris = datasets.load_iris()

features, target = iris.data, iris.target

classifier = GaussianNB()

classifier_sigmoid = CalibratedClassifierCV(classifier, cv=2, method="sigmoid")

classifier_sigmoid.fit(features, target)

new_observation = [[2.6, 2.6, 2.6, 0.4]]

classifier_sigmoid.predict_proba(new_observation)

array([[0.31859971, 0.63663451, 0.04476578]])

In [13]:
classifier.fit(features, target).predict_proba(new_observation)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])